package com.example.test_xml.model.enums;

public enum CountryCodes {
    AC("Ascension Island"),
    AD("Andorra"),
    AE("United Arab Emirates"),
    AF("Afghanistan"),
    AG("Antigua and Barbuda"),
    AI("Anguilla"),
    AL("Albania"),
    AM("Armenia"),
    AN("Netherlands Antilles"),
    AO("Angola"),
    AP("African Regional Industrial Property Organization"),
    AQ("Antarctica_ENG"),
    AR("Argentina"),
    AS("American Samoa"),
    AT("Austria"),
    AU("Australia"),
    AW("Aruba"),
    AX("Åland Islands"),
    AZ("Azerbaijan"),
    BA("Bosnia and Herzegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Belgium"),
    BF("Burkina Faso"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BI("Burundi"),
    BJ("Benin"),
    BL("Saint Barthélemy"),
    BM("Bermuda"),
    BN("Brunei Darussalam"),
    BO("Bolivia"),
    BQ("Bonaire, Saint Eustatius and Saba"),
    BR("Brazil"),
    BS("Bahamas"),
    BT("Bhutan"),
    BU("Burma"),
    BV("Bouvet Island"),
    BW("Botswana"),
    BX("Benelux Trademarks and Designs Office"),
    BY("Belarus"),
    BZ("Belize"),
    CA("Canada"),
    CC("Cocos (Keeling) Islands"),
    CD("Congo, The Democratic Republic of the"),
    CF("Central African Republic"),
    CG("Congo"),
    CH("Switzerland"),
    CI("Cote d'Ivoire"),
    CK("Cook Islands"),
    CL("Chile"),
    CM("Cameroon"),
    CN("China"),
    CO("Colombia"),
    CP("Clipperton Island"),
    CR("Costa Rica"),
    CS("Serbia and Montenegro"),
    CU("Cuba"),
    CV("Cape Verde"),
    CW("Curaçao"),
    CX("Christmas Island"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DE("Germany"),
    DG("Diego Garcia"),
    DJ("Djibouti"),
    DK("Denmark"),
    DM("Dominica"),
    DO("Dominican Republic"),
    DY("Benin"),
    DZ("Algeria"),
    EA("Ceuta, Melilla"),
    EC("Ecuador"),
    EE("Estonia"),
    EF("Union of Countries under the European Community Patent Convention"),
    EG("Egypt"),
    EH("Western Sahara"),
    EM("European Trademark Office"),
    EP("European Patent Organization"),
    ER("Eritrea"),
    ES("Spain"),
    ET("Ethiopia"),
    EU("European Union"),
    EV("Eurasian Patent Organization"),
    EW("Estonia"),
    FI("Finland"),
    FJ("Fiji"),
    FK("Falkland Islands (Malvinas)"),
    FL("Liechtenstein"),
    FM("Micronesia, Federated States of"),
    FO("Faroe Islands"),
    FR("France"),
    FX("France, Metropolitan"),
    GA("Gabon"),
    GB("United Kingdom"),
    GC("Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)"),
    GD("Grenada"),
    GE("Georgia"),
    GF("French Guiana"),
    GG("Guernsey"),
    GH("Ghana"),
    GI("Gibraltar"),
    GL("Greenland"),
    GM("Gambia"),
    GN("Guinea"),
    GP("Guadeloupe"),
    GQ("Equatorial Guinea"),
    GR("Greece"),
    GS("South Georgia and the South Sandwich Islands"),
    GT("Guatemala"),
    GU("Guam"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hong Kong"),
    HM("Heard Island and McDonald Islands"),
    HN("Honduras"),
    HR("Croatia"),
    HT("Haiti"),
    HU("Hungary"),
    IB("International Bureau of WIPO"),
    IC("Canary Islands"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IM("Isle of Man"),
    IN("India"),
    IO("British Indian Ocean Territory"),
    IQ("Iraq"),
    IR("Iran, Islamic Republic of"),
    IS("Iceland"),
    IT("Italy"),
    JA("Jamaica"),
    JE("Jersey"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kyrgyzstan"),
    KH("Cambodia"),
    KI("Kiribati"),
    KM("Comoros"),
    KN("Saint Kitts and Nevis"),
    KP("Korea, Democratic People's Republic of"),
    KR("Korea, Republic of"),
    KS("Kosovo (Old - KS)"),
    KW("Kuwait"),
    KY("Cayman Islands"),
    KZ("Kazakhstan"),
    LA("Lao People's Democratic Republic"),
    LB("Lebanon"),
    LC("Saint Lucia"),
    LF("Libya Fezzan"),
    LI("Liechtenstein"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesotho"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libyan Arab Jamahiriya"),
    MA("Morocco"),
    MC("Monaco"),
    MD("Moldova, Republic of"),
    ME("Montenegro"),
    MF("Saint Martin (French Part)"),
    MG("Madagascar"),
    MH("Marshall Islands"),
    MK("Macedonia, The Former Yugoslav Republic of"),
    ML("Mali"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macau"),
    MP("Northern Mariana Islands"),
    MQ("Martinique"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU("Mauritius"),
    MV("Maldives"),
    MW("Malawi"),
    MX("Mexico"),
    MY("Malaysia"),
    MZ("Mozambique"),
    NA("Namibia"),
    NC("New Caledonia"),
    NE("Niger"),
    NF("Norfolk Island"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Netherlands"),
    NO("Norway"),
    NP("Nepal"),
    NR("Nauru"),
    NT("Neutral Zone"),
    NU("Niue"),
    NZ("New Zealand"),
    OA("African Intellectual Property Organization"),
    OM("Oman"),
    PA("Panama"),
    PE("Peru"),
    PF("French Polynesia"),
    PG("Papua New Guinea"),
    PH("Philippines"),
    PI("Philippines"),
    PK("Pakistan"),
    PL("Poland"),
    PM("Saint Pierre and Miquelon"),
    PN("Pitcairn"),
    PR("Puerto Rico"),
    PS("Palestinian Territory, Occupied"),
    PT("Portugal"),
    PW("Palau"),
    PY("Paraguay"),
    QA("Qatar"),
    RA("Argentina"),
    RB("Bolivia [cf. Botswana: identical code element]"),
    RC("China"),
    RE("Reunion"),
    RH("Haiti"),
    RI("Indonesia"),
    RL("Lebanon"),
    RM("Madagascar"),
    RN("Niger"),
    RO("Romania"),
    RP("Philippines"),
    RS("Serbia"),
    RU("Russian Federation"),
    RW("Rwanda"),
    SA("Saudi Arabia"),
    SB("Solomon Islands"),
    SC("Seychelles"),
    SD("Sudan"),
    SE("Sweden"),
    SF("Finland"),
    SG("Singapore"),
    SH("Saint Helena"),
    SI("Slovenia"),
    SJ("Svalbard and Jan Mayen"),
    SK("Slovakia"),
    SL("Sierra Leone"),
    SM("San Marino"),
    SN("Senegal"),
    SO("Somalia"),
    SR("Suriname"),
    SS("South Sudan"),
    ST("Sao Tome and Principe"),
    SU("USSR"),
    SV("El Salvador"),
    SX("Sint Maarten (Dutch part)"),
    SY("Syrian Arab Republic"),
    SZ("Swaziland"),
    TA("Tristan da Cunha"),
    TC("Turks and Caicos Islands"),
    TD("Chad"),
    TF("French Southern Territories"),
    TG("Togo"),
    TH("Thailand"),
    TJ("Tajikistan"),
    TK("Tokelau"),
    TL("Timor-Leste"),
    TM("Turkmenistan"),
    TN("Tunisia"),
    TO("Tonga"),
    TP("East Timor"),
    TR("Turkey"),
    TT("Trinidad and Tobago"),
    TV("Tuvalu"),
    TW("Taiwan, Province of China"),
    TZ("Tanzania, United Republic of"),
    UA("Ukraine"),
    UG("Uganda"),
    UK("United Kingdom"),
    UM("United States Minor Outlying Islands"),
    UN("United Nations"),
    US("United States"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VA("Holy See (Vatican City State)"),
    VC("Saint Vincent and the Grenadines"),
    VE("Venezuela"),
    VG("Virgin Islands, British"),
    VI("Virgin Islands, U.S."),
    VN("Viet Nam"),
    VU("Vanuatu"),
    WF("Wallis and Futuna"),
    WG("Grenada"),
    WL("Saint Lucia"),
    WO("World Intellectual Property Organization"),
    WS("Samoa"),
    YE("Yemen"),
    YT("Mayotte"),
    ZA("South Africa"),
    ZM("Zambia"),
    ZW("Zimbabwe");

    private final String description;

    CountryCodes(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
