package com.example.test_xml.model.enums;

public enum ReportIndicatorTypes {
    CFIR3("A/C Opening Documents"),
    SB01("Activating of dormant account"),
    AIF("Additional Information File"),
    AIFT("Additional Information File (T)"),
    SB20("Adverse news on media"),
    D1("Assistance Letter Required"),
    C5("Associates (PE): Foreign Remittances (Inward/Outward)"),
    C1("Associates (PE): PE Details Only"),
    C2("Associates (PE): Related Account Details"),
    C4("Associates (PE): Related Account Opening Documents (KYC)"),
    C3("Associates (PE): Related Bank Statements"),
    C7("Associates (PE): Retain CCTV Footages for Related Accounts"),
    C6("Associates (PE): Western Union TransactionResponse"),
    SB21("Attempted transactions"),
    SB22("Bribery"),
    BRS("BRS - Banking Relations Summary"),
    BRSC("BRS Confirmation - I confirm that all the relevant accounts available are included in the Banking Relations Summary"),
    CFIR2("CDD Report"),
    CFIR1("Copies of Identification Documents"),
    SB19("Counterfeit Notes"),
    CTR("CTR"),
    SB04("Customer suspected of having terrorist links"),
    SB23("Digital currency/ digital assets"),
    SB24("Drug dealing"),
    SB13("Drugs"),
    EFT("EFT"),
    SB25("Frauds"),
    SB26("Frauds related to cheques"),
    SB03("Frequent transactions below the mandatory reporting threshold level (Rs. 1,000,000)"),
    SB05("Funds originating from a suspicious organization/individual (known terrorist front organizations, shell companies etc.)"),
    SB16("Human Trafficking"),
    SB27("Identified as a Politically Exposed Person (PEP)"),
    IFT("IFT"),
    SB17("Illegal Imports/Exports"),
    LKFNS("LankaFIN STRs"),
    SB10("Large unusual inward remittance from a suspicious organization"),
    SB08("Large/ unusual inward/ outward remittance"),
    SB02("Large/Unusual cash deposit/withdrawal not consistent with the known pattern of transactions"),
    A1("Money Laundering"),
    SB28("Not registered with the NGO secretariat"),
    SB29("Ongoing court case/ police investigations"),
    OTH("Other"),
    SB30("Payment devices frauds"),
    SB31("Positive matches in sanction screening/ watch lists"),
    SB32("Pyramid scheme"),
    SB07("Regular unusual offshore activity"),
    SB33("Related to DNFBP sector - Accountants"),
    SB34("Related to DNFBP sector - Casino"),
    SB35("Related to DNFBP sector - Company secretaries"),
    SB38("Related to DNFBP sector - Other"),
    SB36("Related to DNFBP sector - Real estate agents"),
    SB37("Related to DNFBP sector -Gem and Jewelry dealers"),
    SB06("Reluctance to divulge identification and other information"),
    SB39("Remittance from high risk countries"),
    S02("Reportable Suspicious TransactionResponse - NO"),
    S01("Reportable Suspicious TransactionResponse - YES"),
    SB40("Sanctions screening (No. 1267, 1373, 1718, 2231)"),
    SB41("Scam - A police compliant is available"),
    SB42("Scam - Police complaint is not available"),
    SB43("Submission of forged NIC or any other identification documents"),
    B5("Targets: Foreign Remittances (Inward/Outward)"),
    B1("Targets: PAE Details Only"),
    B2("Targets: Related Account Details"),
    B4("Targets: Related Account Opening Documents (KYC)"),
    B3("Targets: Related Bank Statements"),
    B7("Targets: Retain CCTV Footages for Related Accounts"),
    B6("Targets: Western Union TransactionResponse"),
    SB14("Tax Evasion"),
    A2("Terrorist Financing"),
    SB44("Third party deposits related to Hawala, Undiyal…etc"),
    SB09("Transaction without an economic rationale"),
    SB45("Unusual customer behavior"),
    E1("Urgent"),
    SB11("Usage of forged documents"),
    SB46("Violations under the Customs Ordinance"),
    SB47("Violations under the Excise Ordinance"),
    SB48("Violations under the Foreign Exchange Act"),
    SB18("Virtual Currencies");

    private final String description;

    ReportIndicatorTypes(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
